trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node.js dependencies'

- powershell: |
    Start-Process -FilePath "npm" -ArgumentList "start" -NoNewWindow
    Start-Sleep -Seconds 30
  displayName: 'Start Node.js server'

- bash: | 
   echo $(targetURL)
   chmod -R 777  ./
   docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t $(targetURL) -J report.json -r report.html 
   true
  displayName: 'Owasp Container Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/report.html'
    artifact: 'ZAP Report'
  displayName: 'Publish ZAP Report'