trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node.js dependencies'

- script: |
    npm start &
    sleep 30
  displayName: 'Start Node.js server'

- bash: | 
   echo $(targetURL)
   chmod -R 777  ./
   docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t $(apiURL) -J report.json -r report.html 
   true
  displayName: 'Owasp Container Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/report.html'
    artifact: 'ZAP Report'
  displayName: 'Publish ZAP Report'

- bash: | 
    curl --max-time 60 "https://html5.validator.nu/?doc=$(apiURL)" > html_validation_report.html
  displayName: 'Call HTML Validation API'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: html_validation_report.html
    ArtifactName: 'UI_Validation'
    publishLocation: 'Container'    

- bash: | 
    curl --max-time 60 "https://jigsaw.w3.org/css-validator/validator?text=$(text)&warning=$(warning)&profile=$(profile)" > css_validation_report.html
  displayName: 'Call CSS Validation API'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'css_validation_report.html'
    ArtifactName: 'UI_Validation'
    publishLocation: 'Container'      