trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node.js dependencies'

- script: |
    Start-Process -FilePath "npm" -ArgumentList "start" -NoNewWindow
    Start-Sleep -Seconds 30
  displayName: 'Start Node.js server'

- powershell: |
   .\zap_scan.ps1
  displayName: 'Run ZAP Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/zap_report.html'
    artifact: 'ZAP Report'
  displayName: 'Publish ZAP Report'