trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Node.js dependencies'

- powershell: |
    # Download and install ZAP
    Invoke-WebRequest -Uri "https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2_10_0_windows.exe" -OutFile "ZAP_2_10_0_windows.exe"
    Start-Process -FilePath "ZAP_2_10_0_windows.exe" -ArgumentList "/S" -Wait

    # Start ZAP in daemon mode
    Start-Process -FilePath "C:\Program Files\OWASP\Zed Attack Proxy\zap.bat" -ArgumentList "-daemon -port 8080" -NoNewWindow -Wait

    # Wait for ZAP to start
    Start-Sleep -Seconds 30

    # Run ZAP scan
    Invoke-WebRequest -Uri "http://localhost:8080/JSON/ascan/action/scan/?url=https://infogaingaiappformultipersona.azurewebsites.net" -Method GET

    # Wait for the scan to complete
    Start-Sleep -Seconds 300

    # Generate report
    Invoke-WebRequest -Uri "http://localhost:8080/OTHER/core/other/htmlreport/" -OutFile "zap_report.html"
  displayName: 'Run ZAP Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/zap_report.html'
    artifact: 'ZAP Report'
  displayName: 'Publish ZAP Report'